"""Synthetic L3 fixtures: a solid block above a solid plate (mm-t-s), mesh in an include.

The files in ``tests/l3/fixtures`` are generated by :func:`write_fixtures`; a test regenerates them and
compares bytes, so they stay reproducible and contain no private model data.

Plate: part 1, 4 x 4 x 1 hexahedra over x, y in [-20, 20], z in [0, 4]; nodes 1-50, elements 1-16.
Block: part 2, 2 x 2 x 2 hexahedra over x, y in [-5, 5], z in [5, 15]; nodes 101-127, elements 101-108.
"""
from __future__ import annotations

from pathlib import Path

FIXTURES = Path(__file__).parents[2] / "tests" / "l3" / "fixtures"
PLATE = dict(base=0, ebase=0, pid=1, n=(4, 4, 1), lo=(-20.0, -20.0, 0.0), hi=(20.0, 20.0, 4.0))
BLOCK = dict(base=100, ebase=100, pid=2, n=(2, 2, 2), lo=(-5.0, -5.0, 5.0), hi=(5.0, 5.0, 15.0))


def _brick(base: int, ebase: int, pid: int, n: tuple[int, int, int], lo: tuple[float, ...],
           hi: tuple[float, ...]) -> tuple[list[str], list[str]]:
    nx, ny, nz = n

    def node(i: int, j: int, k: int) -> int:
        return base + 1 + i + (nx + 1) * (j + (ny + 1) * k)

    nodes = []
    for k in range(nz + 1):
        for j in range(ny + 1):
            for i in range(nx + 1):
                xyz = [lo[a] + (hi[a] - lo[a]) * t / m for a, (t, m) in enumerate(((i, nx), (j, ny), (k, nz)))]
                nodes.append(f"{node(i, j, k):>8}" + "".join(f"{v:>16.6f}" for v in xyz) + f"{0:>8}{0:>8}")
    elements = []
    eid = ebase
    for k in range(nz):
        for j in range(ny):
            for i in range(nx):
                eid += 1
                ring = [(i, j), (i + 1, j), (i + 1, j + 1), (i, j + 1)]
                conn = [node(a, b, k) for a, b in ring] + [node(a, b, k + 1) for a, b in ring]
                elements.append(f"{eid:>8}{pid:>8}" + "".join(f"{c:>8}" for c in conn))
    return nodes, elements


def mesh_text() -> str:
    plate_nodes, plate_elements = _brick(**PLATE)
    block_nodes, block_elements = _brick(**BLOCK)
    lines = ["*KEYWORD", "$ L3 fixture mesh: plate (part 1) and block (part 2), mm", "*NODE",
             *plate_nodes, *block_nodes, "*ELEMENT_SOLID", *plate_elements, *block_elements, "*END"]
    return "\n".join(lines) + "\n"


def main_text(block_section: int = 1) -> str:
    """Main deck; ``block_section`` other than 1 leaves part 2 referring to an undefined section."""
    lines = [
        "*KEYWORD",
        "*TITLE",
        "L3 fixture: block above plate, units mm-t-s (mm, tonne, s, N, MPa)",
        "*CONTROL_TERMINATION",
        "$#  endtim    endcyc     dtmin    endeng    endmas",
        f"{1.0e-5:>10}{0:>10}{0.0:>10}{0.0:>10}{0.0:>10}",
        "*DATABASE_BINARY_D3PLOT",
        "$#      dt      lcdt      beam     npltc    psetid",
        f"{5.0e-5:>10}{0:>10}{0:>10}{0:>10}{0:>10}",
        "*PART",
        "plate",
        "$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid",
        f"{1:>10}{1:>10}{1:>10}{0:>10}{0:>10}{0:>10}{0:>10}{0:>10}",
        "*PART",
        "block",
        f"{2:>10}{block_section:>10}{2:>10}{0:>10}{0:>10}{0:>10}{0:>10}{0:>10}",
        "*SECTION_SOLID",
        "$#   secid    elform       aet",
        f"{1:>10}{1:>10}{0:>10}",
        "*MAT_ELASTIC",
        "$#     mid        ro         e        pr        da        db  not used",
        f"{1:>10}{7.85e-9:>10}{210000.0:>10}{0.3:>10}{0.0:>10}{0.0:>10}{0:>10}",
        "*MAT_ELASTIC",
        f"{2:>10}{7.85e-9:>10}{200000.0:>10}{0.29:>10}{0.0:>10}{0.0:>10}{0:>10}",
        "*INCLUDE",
        "impact_mesh.k",
        "*END",
    ]
    return "\n".join(lines) + "\n"


def fixture_texts() -> dict[str, str]:
    return {"impact.k": main_text(), "impact_broken.k": main_text(block_section=3), "impact_mesh.k": mesh_text()}


def write_fixtures(directory: Path = FIXTURES) -> list[Path]:
    directory.mkdir(parents=True, exist_ok=True)
    written = []
    for name, text in fixture_texts().items():
        path = directory / name
        path.write_bytes(text.encode("ascii"))
        written.append(path)
    return written


if __name__ == "__main__":
    for path in write_fixtures():
        print(path)
